[package]
name = "rusty-vegetation"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
winit = "0.27.5"
cgmath = "0.18.0"
env_logger = "0.9.1"
log = "0.4.17"
wgpu = "0.14.0"
pollster = "0.2.5"
bytemuck = { version = "1.12.2", features = [ "derive" ] }
random-number = "0.1.8"
is-odd = "1.0.0"
